os:
  - linux
  - osx

osx_image: xcode9.3

language: android

jdk:
  - oraclejdk8

before_install: if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then .buildscript/before_linux.sh; fi

install: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew :sqldelight-runtime:build :drivers:native-driver:iosTest :sqldelight-gradle-plugin:test; else ./gradlew build assembleAndroidTest --stacktrace; fi

before_script: if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then android-wait-for-emulator; adb shell input keyevent 82; fi

script: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then .buildscript/deploy_snapshot.sh ":sqldelight-runtime:publish :drivers:native-driver:publish :extensions:coroutines-extensions:publish"; else ./gradlew connectedCheck --stacktrace; fi

after_success: if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then .buildscript/deploy_snapshot.sh uploadArchives; fi

env:
  global:
    - GRADLE_OPTS: "-Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    - secure: "vkFMccJMRLUUHNOZUsmBDT1JaPN0leZ7q3V/hZO95qsIk6hZ9A8jmwvmaohBNytOY3XkTnTqhdpWXaxAqneS/pBAb8MuU/GK7V6Q4rLKI9aC/EiVIHXJcSAevKFQp3quZuFOVvz+wGUX5VoxPvf1kP5o4fgpgrpxcEhE3kr4c/GSJu7bwMc85z1MSmliscF3TjrJJyfrok1hBVXpcu/TCpc2oNZdIrM37UPJIf4KPt7qertdd1mu8bzpEgFWyzOyfNFbZJ1SSbbIQtDIRsv7FAl1raLD8XPG2hY6EhnM9knw4ilYbIjIk/CrNL8wTZI1z+mV8s5MBMn+dZg1xXi5ziLlIjGEBsF5SLL8LglqvKiQrSWDUb+brej33U9DPznRkcLejVanrExetZEfK/v/X0zn2zjFLvh1FF+YqGv9qoiiZQLivv69CICmQcZ+b/QpMrOZBX3WwCqJuOw34DpMqo0YySFxX2dskVMMvqkiym/KSlhuuKl9rk+kHr4eYdFsqDqOZtlScTD7g8RDlOhTiFDaGjQeM7J1OXOpemkK/pDaQ67Qe4TeqJe3maznSb4Rv6EMMgPC0ujwaFsmiPIc5QAVj5gEnHYGl2SzyOfStAED1c4AYE4uJvrkVP5r0aRPNDcYl8vAe/UkYlyyeWcImJ3t57e+xYyDkJyAeQZwaA8="
    - secure: "VSl+7BXEQn2eKoMl3hgUslUMsd8cXsQijAuGQ8gcpzDFZlneJIQ7fC4a1WVGBdgjr87B3mtRfPN7lUL7qbhLPjq7RfTnO6+EyfWgwMXNWHqvPtTskSGh4++rieF5fO+vbFUIjx4InsxetS3dMdmaXPurDpZ+ma+OHNYnoVhhB1QQDq1GzJi/JySRmGUwaEnz+C79YdNK91apFrvIbKmk3q67ZqCON+Sxb+NcEcgLA95HWU3Ww/Qk29qqMIxf25EPvWUmPtQNEMO8PsP5iATGdXipWECrA1mtZ0iVREUa72rcepxNPsSlRLm/eYttHp6GjSj+ZpnmvIAsbmI0VU40ky0CyWhL8m4aBTJFQzNCi9e3tsSnQzgB0WXa1eY6zMg6FXgGMecW88NIZai1lGwJWiyJcIjpXrQXiy/uQEnK09CNHiVqFsYv5cLAlOFthfSkmZiCsE7QTnks1RTbupAXq2vo2Fo9Jhf2tt8FMW/DvKZ6hs7Me+yjGuyNYe2YA3vFc0sEyDFxkMoxSu9YIbg15UPcZDSDjYNRl4IoeH0BSUiwZ8sL7m2N2FWdLjSiFL4+YIHkKBg21VOK5f51FTTpZQ5jyLamq7JEgBkGC6ZVFH59XfewVX87Z8kF43CH+HBfMZ4kIRrJBqCU8AKbM3uavHoMfcHfEKPzDMhL+JL9M8Q="

branches:
  except:
    - gh-pages

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/
