site_name: SQLDelight
site_url: https://cashapp.github.io/sqldelight/
repo_name: sqldelight
repo_url: https://github.com/cashapp/sqldelight
site_description: "SQLDelight - Generates typesafe Kotlin APIs from SQL"
site_author: Square, Inc.
copyright: 'Copyright &copy; 2023 Square, Inc.'
remote_branch: gh-pages

nav:
  - 'SQLDelight':
    - 'Overview': index.md
    - 'Upgrading to 2.0': upgrading-2.0.md
    - 'Changelog': changelog.md
    - 'Contributing': contributing.md
    - 'Code of Conduct': code_of_conduct.md

  - 'SQLite (Android)':
    - 'Getting Started': android_sqlite/index.md
    - 'SQL':
      - 'Foreign Keys': android_sqlite/foreign_keys.md
      - 'Type Projections': android_sqlite/custom_projections.md
      - 'Arguments': android_sqlite/query_arguments.md
      - 'Types': android_sqlite/types.md
      - 'Transactions': android_sqlite/transactions.md
      - 'Grouping Statements': android_sqlite/grouping_statements.md
    - 'Extensions':
        - 'RxJava': android_sqlite/rxjava.md
        - 'Coroutines': android_sqlite/coroutines.md
        - 'AndroidX Paging': android_sqlite/androidx_paging.md
    - 'Migrations': android_sqlite/migrations.md
    - 'Testing': android_sqlite/testing.md
    - 'IntelliJ Plugin': android_sqlite/intellij_plugin.md
    - 'Gradle': android_sqlite/gradle.md
    - '2.x API':
        - 'coroutines-extensions': 2.x/extensions/coroutines-extensions/index.html
        - 'rxjava2-extensions': 2.x/extensions/rxjava2-extensions/index.html
        - 'rxjava3-extensions': 2.x/extensions/rxjava3-extensions/index.html
        - 'androidx-paging3': 2.x/extensions/androidx-paging3/index.html
        - 'android-driver': 2.x/drivers/android-driver/index.html
        - 'runtime': 2.x/runtime/index.html
    - 'Resources': android_sqlite/resources.md


  - 'SQLite (Multiplatform)':
      - 'Getting Started': multiplatform_sqlite/index.md
      - 'SQL':
          - 'Foreign Keys': multiplatform_sqlite/foreign_keys.md
          - 'Type Projections': multiplatform_sqlite/custom_projections.md
          - 'Arguments': multiplatform_sqlite/query_arguments.md
          - 'Types': multiplatform_sqlite/types.md
          - 'Transactions': multiplatform_sqlite/transactions.md
          - 'Grouping Statements': multiplatform_sqlite/grouping_statements.md
      - 'Extensions':
          - 'Coroutines': multiplatform_sqlite/coroutines.md
          - 'AndroidX Paging': multiplatform_sqlite/androidx_paging.md
      - 'Migrations': multiplatform_sqlite/migrations.md
      - 'IntelliJ Plugin': multiplatform_sqlite/intellij_plugin.md
      - 'Gradle': multiplatform_sqlite/gradle.md
      - 'Resources': multiplatform_sqlite/resources.md
      - '2.x API':
          - 'coroutines-extensions': 2.x/extensions/coroutines-extensions/index.html
          - 'runtime': 2.x/runtime/index.html

  - 'MySQL (JVM)':
      - 'Getting Started': jvm_mysql/index.md
      - 'SQL':
          - 'Type Projections': jvm_mysql/custom_projections.md
          - 'Arguments': jvm_mysql/query_arguments.md
          - 'Types': jvm_mysql/types.md
          - 'Transactions': jvm_mysql/transactions.md
          - 'Grouping Statements': jvm_mysql/grouping_statements.md
      - 'Extensions':
          - 'AndroidX Paging': jvm_mysql/androidx_paging.md
      - 'Migrations': jvm_mysql/migrations.md
      - 'IntelliJ Plugin': jvm_mysql/intellij_plugin.md
      - 'Gradle': jvm_mysql/gradle.md
      - '2.x API':
          - 'jdbc-driver': 2.x/drivers/jdbc-driver/index.html
          - 'runtime': 2.x/runtime/index.html

  - 'PostgreSQL (JVM)':
      - 'Getting Started': jvm_postgresql/index.md
      - 'SQL':
          - 'Type Projections': jvm_postgresql/custom_projections.md
          - 'Arguments': jvm_postgresql/query_arguments.md
          - 'Types': jvm_postgresql/types.md
          - 'Transactions': jvm_postgresql/transactions.md
          - 'Grouping Statements': jvm_postgresql/grouping_statements.md
      - 'Extensions':
          - 'AndroidX Paging': jvm_postgresql/androidx_paging.md
      - 'Migrations': jvm_postgresql/migrations.md
      - 'IntelliJ Plugin': jvm_postgresql/intellij_plugin.md
      - 'Gradle': jvm_postgresql/gradle.md
      - '2.x API':
          - 'jdbc-driver': 2.x/drivers/jdbc-driver/index.html
          - 'runtime': 2.x/runtime/index.html

  - 'HSQL (JVM)':
      - 'Getting Started': jvm_h2/index.md
      - 'SQL':
          - 'Type Projections': jvm_h2/custom_projections.md
          - 'Arguments': jvm_h2/query_arguments.md
          - 'Types': jvm_h2/types.md
          - 'Transactions': jvm_h2/transactions.md
          - 'Grouping Statements': jvm_h2/grouping_statements.md
      - 'Extensions':
          - 'AndroidX Paging': jvm_h2/androidx_paging.md
      - 'Migrations': jvm_h2/migrations.md
      - 'IntelliJ Plugin': jvm_h2/intellij_plugin.md
      - 'Gradle': jvm_h2/gradle.md
      - '2.x API':
          - 'jdbc-driver': 2.x/drivers/jdbc-driver/index.html
          - 'runtime': 2.x/runtime/index.html

  - 'SQLite (Native)':
    - 'Getting Started': native_sqlite/index.md
    - 'SQL':
        - 'Foreign Keys': native_sqlite/foreign_keys.md
        - 'Type Projections': native_sqlite/custom_projections.md
        - 'Arguments': native_sqlite/query_arguments.md
        - 'Types': native_sqlite/types.md
        - 'Transactions': native_sqlite/transactions.md
        - 'Grouping Statements': native_sqlite/grouping_statements.md
    - 'Extensions':
        - 'Coroutines': native_sqlite/coroutines.md
        - 'AndroidX Paging': native_sqlite/androidx_paging.md
    - 'Migrations': native_sqlite/migrations.md
    - 'IntelliJ Plugin': native_sqlite/intellij_plugin.md
    - 'Gradle': native_sqlite/gradle.md
    - '2.x API':
        - 'coroutines-extensions': 2.x/extensions/coroutines-extensions/index.html
        - 'native-driver': 2.x/drivers/native-driver/index.html
        - 'runtime': 2.x/runtime/index.html

  - 'SQLite (JVM)':
    - 'Getting Started': jvm_sqlite/index.md
    - 'SQL':
        - 'Foreign Keys': jvm_sqlite/foreign_keys.md
        - 'Type Projections': jvm_sqlite/custom_projections.md
        - 'Arguments': jvm_sqlite/query_arguments.md
        - 'Types': jvm_sqlite/types.md
        - 'Transactions': jvm_sqlite/transactions.md
        - 'Grouping Statements': jvm_sqlite/grouping_statements.md
    - 'Extensions':
        - 'RxJava': jvm_sqlite/rxjava.md
        - 'Coroutines': jvm_sqlite/coroutines.md
        - 'AndroidX Paging': jvm_sqlite/androidx_paging.md
    - 'Migrations': jvm_sqlite/migrations.md
    - 'IntelliJ Plugin': jvm_sqlite/intellij_plugin.md
    - 'Gradle': jvm_sqlite/gradle.md
    - '2.x API':
        - 'coroutines-extensions': 2.x/extensions/coroutines-extensions/index.html
        - 'rxjava2-extensions': 2.x/extensions/rxjava2-extensions/index.html
        - 'rxjava3-extensions': 2.x/extensions/rxjava3-extensions/index.html
        - 'sqlite-driver': 2.x/drivers/sqlite-driver/index.html
        - 'runtime': 2.x/runtime/index.html

  - 'SQLite (JS)':
      - 'Getting Started': js_sqlite/index.md
      - 'Multiplatform': js_sqlite/multiplatform.md
      - 'Web Workers':
          - SQL.js Worker: js_sqlite/sqljs_worker.md
          - Custom Workers: js_sqlite/custom_worker.md
      - 'SQL':
          - 'Type Projections': js_sqlite/custom_projections.md
          - 'Arguments': js_sqlite/query_arguments.md
          - 'Types': js_sqlite/types.md
          - 'Transactions': js_sqlite/transactions.md
          - 'Grouping Statements': js_sqlite/grouping_statements.md
      - 'Extensions':
          - 'Coroutines': js_sqlite/coroutines.md
          - 'AndroidX Paging': js_sqlite/androidx_paging.md
      - 'Migrations': js_sqlite/migrations.md
      - 'IntelliJ Plugin': js_sqlite/intellij_plugin.md
      - 'Gradle': js_sqlite/gradle.md
      - '2.x API':
          - 'coroutines-extensions': 2.x/extensions/coroutines-extensions/index.html
          - 'sqljs-driver': 2.x/drivers/sqljs-driver/index.html
          - 'runtime': 2.x/runtime/index.html

  - '2.x API': 2.x/index.html

theme:
  name: 'material'
  favicon: images/icon-cashapp.png
  logo: images/icon-sqldelight.svg
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      accent: 'green'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: 'green'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - content.tabs.link
    - content.code.annotate
    - content.action.view
    - announce.dismiss

extra_css:
  - 'css/app.css'

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.critic
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - macros
  - mike

extra:
  versions:
    sqldelight: !ENV [SQLDELIGHT_VERSION, 'local-development']
  version:
    provider: mike
