site_name: SQLDelight
site_url: https://cashapp.github.io/sqldelight/
repo_name: sqldelight
repo_url: https://github.com/cashapp/sqldelight
site_description: "SQLDelight - Generates typesafe Kotlin APIs from SQL"
site_author: Square, Inc.
copyright: 'Copyright &copy; 2019 Square, Inc.'
remote_branch: gh-pages

nav:
  - 'Overview': index.md
  - 'Changelog': changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code_of_conduct.md
  - 'Android SQLite':
    - 'Getting Started': android_sqlite/index.md
    - 'SQL':
      - 'Projections': android_sqlite/custom_projections.md
      - 'Arguments': android_sqlite/query_arguments.md
      - 'Types': android_sqlite/types.md
      - 'Transactions': android_sqlite/transactions.md
    - 'Extensions':
        - 'RxJava': android_sqlite/rxjava.md
        - 'Coroutines': android_sqlite/coroutines.md
        - 'Android Paging': android_sqlite/android_paging.md
    - 'Migrations': android_sqlite/migrations.md
    - 'IntelliJ Plugin': android_sqlite/intellij_plugin.md
    - 'Gradle': android_sqlite/gradle.md
    - 'Upgrading Pre-1.0': android_sqlite/upgrading.md
    - '1.x API':
        - 'coroutines-extensions': android_sqlite/1.x/coroutines-extensions/index.html
        - 'native-driver': android_sqlite/1.x/native-driver/index.html
        - 'runtime': android_sqlite/1.x/runtime/index.html
    - 'Resources': android_sqlite/resources.md
  - 'Native SQLite':
    - 'Overview': native_sqlite/index.md
    - 'Custom Projections': native_sqlite/custom_projections.md
    - 'Query Arguments': native_sqlite/query_arguments.md
    - 'Types': native_sqlite/types.md
    - 'Transactions': native_sqlite/transactions.md
    - 'Custom Column Types': native_sqlite/custom_column_types.md
    - 'Migrations': native_sqlite/migrations.md
    - 'Multiplatform': native_sqlite/multiplatform.md
    - 'Gradle': native_sqlite/gradle.md
    - '1.x API':
        - 'coroutines-extensions': native_sqlite/1.x/coroutines-extensions/index.html
        - 'native-driver': native_sqlite/1.x/native-driver/index.html
        - 'runtime': native_sqlite/1.x/runtime/index.html
  - 'JVM SQLite':
      - 'Overview': jvm_sqlite/index.md
      - 'Custom Projections': jvm_sqlite/custom_projections.md
      - 'Query Arguments': jvm_sqlite/query_arguments.md
      - 'Types': jvm_sqlite/types.md
      - 'Transactions': jvm_sqlite/transactions.md
      - 'Custom Column Types': jvm_sqlite/custom_column_types.md
      - 'Migrations': jvm_sqlite/migrations.md
      - 'Multiplatform': jvm_sqlite/multiplatform.md
      - 'Gradle': jvm_sqlite/gradle.md
      - '1.x API':
          - 'coroutines-extensions': jvm_sqlite/1.x/coroutines-extensions/index.html
          - 'native-driver': jvm_sqlite/1.x/native-driver/index.html
          - 'runtime': jvm_sqlite/1.x/runtime/index.html
  - 'JVM MySql':
      - 'Overview': jvm_mysql/index.md
      - 'Custom Projections': jvm_mysql/custom_projections.md
      - 'Query Arguments': jvm_mysql/query_arguments.md
      - 'Types': jvm_mysql/types.md
      - 'Transactions': jvm_mysql/transactions.md
      - 'Custom Column Types': jvm_mysql/custom_column_types.md
      - 'Migrations': jvm_mysql/migrations.md
      - 'Multiplatform': jvm_mysql/multiplatform.md
      - 'Gradle': jvm_mysql/gradle.md
      - '1.x API':
          - 'coroutines-extensions': jvm_mysql/1.x/coroutines-extensions/index.html
          - 'native-driver': jvm_mysql/1.x/native-driver/index.html
          - 'runtime': jvm_mysql/1.x/runtime/index.html
  - 'Multiplatform SQLite':
      - 'Overview': multiplatform_sqlite/index.md
      - 'Custom Projections': multiplatform_sqlite/custom_projections.md
      - 'Query Arguments': multiplatform_sqlite/query_arguments.md
      - 'Types': multiplatform_sqlite/types.md
      - 'Transactions': multiplatform_sqlite/transactions.md
      - 'Custom Column Types': multiplatform_sqlite/custom_column_types.md
      - 'Migrations': multiplatform_sqlite/migrations.md
      - 'Gradle': multiplatform_sqlite/gradle.md
      - '1.x API':
          - 'coroutines-extensions': multiplatform_sqlite/1.x/coroutines-extensions/index.html
          - 'native-driver': multiplatform_sqlite/1.x/native-driver/index.html
          - 'runtime': multiplatform_sqlite/1.x/runtime/index.html

theme:
  name: 'material'
  favicon: images/icon-cashapp.png
  logo: images/icon-cashapp.png
  palette:
    primary: 'deep purple'
    accent: 'pink'
  feature:
    tabs: true

extra_css:
  - 'css/app.css'

markdown_extensions:
  - codehilite:
      guess_lang: false

plugins:
  - search
  - macros

extra:
  versions:
    sqldelight: '1.3.0'
