[versions]
kotlin = "1.5.31"
dokka = "1.4.32"
kotlinCoroutines = "1.5.2"
idea = "202.8194.7"
androidxSqlite = "2.1.0"
schemaCrawler = "14.16.04.01-java7"
stately = "1.1.10"
sqliter = "1.0.10"
testhelp = "0.5.5"
sqljs = "1.6.2"
paging = "2.1.2"
paging3 = "3.1.0"
ktlint = "0.43.0"
test = "1.4.0"
agp = "4.2.2"
compileSdk = "31"
minSdk = "14"

[libraries]
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-commonAnnotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-test-core = { module = "androidx.test:core", version.ref = "test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidxSqlite" }
androidx-sqliteFramework = { module = "androidx.sqlite:sqlite-framework", version.ref = "androidxSqlite" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-paging3-common = { module = "androidx.paging:paging-common", version.ref = "paging3" }
androidx-paging3-rx3 = { module = "androidx.paging:paging-rxjava3", version.ref = "paging3" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.10.2" }
junit = { module = "junit:junit", version = "4.13.2" }
jgrapht = { module = "org.jgrapht:jgrapht-core", version = "1.5.1" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
turbine = { module = "app.cash.turbine:turbine", version = "0.7.0" }
bugsnag = { module = "com.bugsnag:bugsnag", version = "3.6.3" }

intellij-java = { module = "com.jetbrains.intellij.java:java-psi", version.ref = "idea" }
intellij-core = { module = "com.jetbrains.intellij.platform:core-impl", version.ref = "idea" }
intellij-lang = { module = "com.jetbrains.intellij.platform:lang-impl", version.ref = "idea" }
intellij-testFramework = { module = "com.jetbrains.intellij.platform:test-framework", version.ref = "idea" }
intellij-analysis = { module = "com.jetbrains.intellij.platform:analysis", version.ref = "idea" }
intellij-analysisImpl = { module = "com.jetbrains.intellij.platform:analysis-impl", version.ref = "idea" }
intellij-indexing = { module = "com.jetbrains.intellij.platform:indexing-impl", version.ref = "idea" }
intellij-asm = { module = "org.jetbrains.intellij.deps:asm-all", version = "7.0.1" }

sqlitePsi = { module = "com.alecstrong:sqlite-psi-core", version = "0.3.15" }
sqliteJdbc = { module = "org.xerial:sqlite-jdbc", version = "3.34.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.7.3" }
rxJava2 = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21" }
rxJava3 = { module = "io.reactivex.rxjava3:rxjava", version = "3.1.3" }
guava = { module = "com.google.guava:guava", version = "23.6.1-jre" }

schemaCrawler-tools = { module = "us.fatehi:schemacrawler-tools", version.ref = "schemaCrawler" }
schemaCrawler-sqlite = { module = "us.fatehi:schemacrawler-sqlite", version.ref = "schemaCrawler" }

objectDiff = { module = "de.danielbechler:java-object-diff", version = "0.95" }
sqliter = { module = "co.touchlab:sqliter-driver", version.ref = "sqliter" }
stately-core = { module = "co.touchlab:stately-common", version.ref = "stately" }
stately-concurrency = { module = "co.touchlab:stately-concurrency", version.ref = "stately" }
stately-collections = { module = "co.touchlab:stately-collections", version.ref = "stately" }

testhelp = { module = "co.touchlab:testhelp", version.ref = "testhelp" }
burst = { module = "com.squareup.burst:burst-junit4", version = "1.2.0" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
intellij = { id = "org.jetbrains.intellij", version = "1.1.2" }
grammarKit = { id = "org.jetbrains.grammarkit", version = "2021.1.3" }
grammarKitComposer = { id = "com.alecstrong.grammar.kit.composer", version = "0.1.5" }
publish = { id = "com.vanniktech.maven.publish", version = "0.14.2" }
spotless = { id = "com.diffplug.spotless", version = "6.0.3" }
changelog = { id = "org.jetbrains.changelog", version = "1.3.1" }
shadow = { id = "com.github.johnrengelman.shadow", version = "6.1.0" }