[versions]
kotlin = "1.8.0"
dokka = "1.7.20"
kotlinCoroutines = "1.6.4"
idea = "221.6008.13" # Electric Eel (2022.1.1) RC 1 (see https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html)
androidxSqlite = "2.2.0"
schemaCrawler = "16.19.2"
stately = "1.2.3"
sqliter = "1.2.2"
testhelp = "0.6.4"
sqljs = "1.6.2"
paging-mpp = "3.1.1-0.1.1"
paging3 = "3.1.1"
ktlint = "0.46.1"
agp = "7.4.0"
compileSdk = "31"
minSdk = "16"
sqlPsi = "0.5.0-SNAPSHOT"
testContainers = "1.17.6"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "kotlinCoroutines" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-test-core = "androidx.test:core:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidxSqlite" }
androidx-sqliteFramework = { module = "androidx.sqlite:sqlite-framework", version.ref = "androidxSqlite" }
app-cash-paging-common = { module = "app.cash.paging:paging-common", version.ref = "paging-mpp" }
app-cash-paging-runtime = { module = "app.cash.paging:paging-runtime", version.ref = "paging-mpp" }
androidx-paging3-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging3" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }
junit = { module = "junit:junit", version = "4.13.2" }
jgrapht = { module = "org.jgrapht:jgrapht-core", version = "1.5.1" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
turbine = { module = "app.cash.turbine:turbine", version = "0.12.1" }
bugsnag = { module = "com.bugsnag:bugsnag", version = "3.6.4" }
picnic = { module = "com.jakewharton.picnic:picnic", version = "0.6.0" }
moshi = { module = "com.squareup.moshi:moshi", version = "1.14.0" }
moshiCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version = "1.14.0" }

intellij-core = { module = "com.jetbrains.intellij.platform:core", version.ref = "idea" }
intellij-coreImpl = { module = "com.jetbrains.intellij.platform:core-impl", version.ref = "idea" }
intellij-core-ui = { module = "com.jetbrains.intellij.platform:core-ui", version.ref = "idea" }
intellij-ideImpl = { module = "com.jetbrains.intellij.platform:ide-impl", version.ref = "idea" }
intellij-testFramework = { module = "com.jetbrains.intellij.platform:test-framework", version.ref = "idea" }
intellij-lang = { module = "com.jetbrains.intellij.platform:lang", version.ref = "idea" }
intellij-langImpl = { module = "com.jetbrains.intellij.platform:lang-impl", version.ref = "idea" }
intellij-analysis = { module = "com.jetbrains.intellij.platform:analysis", version.ref = "idea" }
intellij-analysisImpl = { module = "com.jetbrains.intellij.platform:analysis-impl", version.ref = "idea" }
intellij-android = { module = "com.jetbrains.intellij.android:android-adt-ui-model", version.ref = "idea" }
intellij-projectModel = { module = "com.jetbrains.intellij.platform:project-model", version.ref = "idea" }
intellij-projectModelImpl = { module = "com.jetbrains.intellij.platform:project-model-impl", version.ref = "idea" }

jna = { module = "net.java.dev.jna:jna", version = "5.13.0" }

sqlPsi = { module = "app.softwork.sql.psi:core", version.ref = "sqlPsi" }
sqlPsiTestFixtures  = { module = "app.softwork.sql.psi:test-fixtures", version.ref = "sqlPsi" }
robolectric = { module = "org.robolectric:robolectric", version = "4.9.2" }
rxJava2 = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21" }
rxJava3 = { module = "io.reactivex.rxjava3:rxjava", version = "3.1.6" }
sqliteJdbc = { module = "org.xerial:sqlite-jdbc", version = "3.40.0.0" }
postgresJdbc = { module = "org.postgresql:postgresql", version = "42.5.1" }
mysqlJdbc = { module = "mysql:mysql-connector-java", version = "8.0.32" }

schemaCrawler-tools = { module = "us.fatehi:schemacrawler-tools", version.ref = "schemaCrawler" }
schemaCrawler-sqlite = { module = "us.fatehi:schemacrawler-sqlite", version.ref = "schemaCrawler" }

objectDiff = { module = "de.danielbechler:java-object-diff", version = "0.95" }
sqliter = { module = "co.touchlab:sqliter-driver", version.ref = "sqliter" }
stately-core = { module = "co.touchlab:stately-common", version.ref = "stately" }
stately-concurrency = { module = "co.touchlab:stately-concurrency", version.ref = "stately" }
stately-collections = { module = "co.touchlab:stately-collections", version.ref = "stately" }

testhelp = { module = "co.touchlab:testhelp", version.ref = "testhelp" }
burst = { module = "com.squareup.burst:burst-junit4", version = "1.2.0" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.10" }

r2dbc = { module = "io.r2dbc:r2dbc-spi", version = "1.0.0.RELEASE" }
testContainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testContainers" }
testContainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testContainers" }
testContainers-r2dbc = { module = "org.testcontainers:r2dbc", version.ref = "testContainers" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
intellij = { id = "org.jetbrains.intellij", version = "1.12.0" }
grammarKitComposer = { id = "com.alecstrong.grammar.kit.composer", version = "0.1.11" }
publish = { id = "com.vanniktech.maven.publish", version = "0.20.0" }
spotless = { id = "com.diffplug.spotless", version = "6.13.0" }
changelog = { id = "org.jetbrains.changelog", version = "2.0.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
ksp = { id = "com.google.devtools.ksp", version = "1.8.0-1.0.8" }
