[versions]
kotlin = "2.2.10"
dokka = "2.0.0"
kotlinx-coroutines = "1.10.2"
idea = "231.9392.1" # Hedgehog | 2023.1.1 Patch 2 (see https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html)
androidxSqlite = "2.5.2"
schemaCrawler = "16.19.2"
sqliter = "1.3.3"
sqljs = "1.8.0"
paging-mpp = "3.1.1-0.3.1"
ktlint = "1.7.1"
agp = "8.13.0"
compileSdk = "35"
minSdk = "21"
sqlPsi = "0.6.0"
testContainers = "1.21.3"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinx-browser = "org.jetbrains.kotlinx:kotlinx-browser:0.3"

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "kotlinx-coroutines" }

kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"

androidx-test-core = "androidx.test:core:1.7.0"
androidx-test-runner = "androidx.test:runner:1.6.1"
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidxSqlite" }
androidx-sqliteFramework = { module = "androidx.sqlite:sqlite-framework", version.ref = "androidxSqlite" }
app-cash-paging-common = { module = "app.cash.paging:paging-common", version.ref = "paging-mpp" }
app-cash-paging-runtime-uikit = { module = "app.cash.paging:paging-runtime-uikit", version.ref = "paging-mpp" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

kotlinPoet = { module = "com.squareup:kotlinpoet", version = "2.2.0" }
junit = { module = "junit:junit", version = "4.13.2" }
jgrapht = { module = "org.jgrapht:jgrapht-core", version = "1.5.2" }
truth = { module = "com.google.truth:truth", version = "1.4.5" }
turbine = { module = "app.cash.turbine:turbine", version = "1.2.1" }
bugsnag = { module = "com.bugsnag:bugsnag", version = "3.8.0" }
picnic = { module = "com.jakewharton.picnic:picnic", version = "0.7.0" }

intellij-core = { module = "com.jetbrains.intellij.platform:core", version.ref = "idea" }
intellij-coreImpl = { module = "com.jetbrains.intellij.platform:core-impl", version.ref = "idea" }
intellij-coreUi = { module = "com.jetbrains.intellij.platform:core-ui", version.ref = "idea" }
intellij-ide = { module = "com.jetbrains.intellij.platform:ide", version.ref = "idea" }
intellij-ideCore = { module = "com.jetbrains.intellij.platform:ide-core", version.ref = "idea" }
intellij-ideImpl = { module = "com.jetbrains.intellij.platform:ide-impl", version.ref = "idea" }
intellij-testFramework = { module = "com.jetbrains.intellij.platform:test-framework", version.ref = "idea" }
intellij-lang = { module = "com.jetbrains.intellij.platform:lang", version.ref = "idea" }
intellij-langImpl = { module = "com.jetbrains.intellij.platform:lang-impl", version.ref = "idea" }
intellij-analysis = { module = "com.jetbrains.intellij.platform:analysis", version.ref = "idea" }
intellij-analysisImpl = { module = "com.jetbrains.intellij.platform:analysis-impl", version.ref = "idea" }
intellij-android = { module = "com.jetbrains.intellij.android:android-adt-ui-model", version.ref = "idea" }
intellij-projectModel = { module = "com.jetbrains.intellij.platform:project-model", version.ref = "idea" }
intellij-projectModelImpl = { module = "com.jetbrains.intellij.platform:project-model-impl", version.ref = "idea" }
intellij-utilEx = { module = "com.jetbrains.intellij.platform:util-ex", version.ref = "idea" }
intellij-utilUi = { module = "com.jetbrains.intellij.platform:util-ui", version.ref = "idea" }
intellij-util = { module = "com.jetbrains.intellij.platform:util", version.ref = "idea" }

sqlPsi = { module = "app.cash.sql-psi:core", version.ref = "sqlPsi" }
sqlPsiEnvironment = { module = "app.cash.sql-psi:environment", version.ref = "sqlPsi" }
robolectric = { module = "org.robolectric:robolectric", version = "4.16" }
rxJava2 = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21" }
rxJava3 = { module = "io.reactivex.rxjava3:rxjava", version = "3.1.12" }
sqliteJdbc = { module = "org.xerial:sqlite-jdbc", version = "3.50.3.0" }
postgresJdbc = { module = "org.postgresql:postgresql", version = "42.7.8" }
mysqlJdbc = { module = "mysql:mysql-connector-java", version = "8.0.33" }

schemaCrawler-tools = { module = "us.fatehi:schemacrawler-tools", version.ref = "schemaCrawler" }
schemaCrawler-sqlite = { module = "us.fatehi:schemacrawler-sqlite", version.ref = "schemaCrawler" }

objectDiff = { module = "de.danielbechler:java-object-diff", version = "0.95" }
sqliter = { module = "co.touchlab:sqliter-driver", version.ref = "sqliter" }
stately-concurrency = { module = "co.touchlab:stately-concurrency", version = "2.1.0" }

testhelp = { module = "co.touchlab:testhelp", version = "0.6.13" }
burst = { module = "com.squareup.burst:burst-junit4", version = "1.2.0" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.19" }

r2dbc = { module = "io.r2dbc:r2dbc-spi", version = "1.0.0.RELEASE" }
testContainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testContainers" }
testContainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testContainers" }
testContainers-r2dbc = { module = "org.testcontainers:r2dbc", version.ref = "testContainers" }

# dummy to get renovate updates.
# The version is used in rootProject build.gradle with spotless.
ktlint-dummy = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
intellij = { id = "org.jetbrains.intellij.platform", version = "2.10.2" }
grammarKitComposer = { id = "app.cash.grammarkit-composer", version = "0.2.0" }
publish = { id = "com.vanniktech.maven.publish", version = "0.32.0" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
changelog = { id = "org.jetbrains.changelog", version = "2.0.0" }
shadow = "com.gradleup.shadow:9.2.2"
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
