name: Test

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        job: [instrumentation, test]
        exclude:
          - os: windows-latest
            job: instrumentation

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache intellij download
        uses: actions/cache@v2.1.0
        with:
          path: lib/download
          key: intellij-${{ hashFiles('gradle/dependencies.gradle') }}
      - name: Cache gradle
        uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run ubuntu tests
        if: matrix.os == 'ubuntu-latest' && matrix.job == 'test'
        run: ./gradlew build -x :sqldelight-idea-plugin:build --stacktrace

      - name: Run the IntelliJ plugin
        if: matrix.os == 'ubuntu-latest' && matrix.job == 'instrumentation'
        run: ./gradlew :sqldelight-idea-plugin:build --stacktrace
      - name: Verify intellij plugin
        if: matrix.os == 'ubuntu-latest' && matrix.job == 'instrumentation'
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
        with:
          ide-versions: |
            ideaIC:2019.1.4
            ideaIU:2019.1.4
            ideaIC:2019.2.4
            ideaIU:2019.2.4
            ideaIC:2019.3.5
            ideaIU:2019.3.5
            ideaIC:2020.1.2
            ideaIU:2020.1.2

      - name: Run windows tests
        if: matrix.os == 'windows-latest'
        run: ./gradlew mingwTest sqldelight-idea-plugin:check --stacktrace

      - name: Run instrumentation tests
        if: matrix.os == 'macOS-latest' && matrix.job == 'instrumentation'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck :sqldelight-gradle-plugin:build --stacktrace -PInstrumentation
      - name: Run ios tests
        if: matrix.os == 'macOS-latest' && matrix.job == 'test'
        run: ./gradlew iosX64Test --stacktrace

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
